CREATE TYPE ROLES AS ENUM('user','admin');
CREATE TABLE users(
  "userId" SERIAL PRIMARY KEY,
  "role" ROLES DEFAULT 'user',
  "username" VARCHAR(32) UNIQUE NOT NULL,
  "password" VARCHAR(128) NOT NULL,
  "createAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "updateAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
