version: "3"
services:
  web:
    build: ./frontend
    container_name: "senior-frontend"
    volumes:
      - ./frontend:/usr/src/service
    # ports:
    #   - "8080:8080"
    command: npm run serve
  api:
    build: ./backend
    container_name: "senior-api"
    command: npm run start:debug
    volumes:
      - ./backend:/usr/src/service
      - ./backend/images:/usr/src/service/images
      - /usr/src/service/node_modules
    working_dir: /usr/src/service
    # ports:
    #   - "3030:3030"
    depends_on:
      - db
      - redis
    environment:
      WAIT_HOSTS: db:5432
  nginx:
    container_name: "senior-nginx"
    restart: always
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/log:/etc/nginx/log
    depends_on:
      - web
      - api
  db:
    build: ./postgresql
    container_name: "senior-db"
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=senior
      - POSTGRES_DB=senior
  redis:
    image: "redis:4-alpine"
    container_name: "senior-redis"
    command: redis-server --requirepass 1234
    ports:
      - "6379:6379"
