module.exports = [
  {
    newsId: "news001",
    newsTitle: "Thailand to get 2 million shots of China’s Sinovac",
    exampleContent:
      "Thailand will get its first lot of Covid-19 vaccines from China’s Sinovac Biotech Ltd next month",
    newsContent:
      "<div><p>Thailand will get its first lot of Covid-19 vaccines from China’s Sinovac Biotech Ltd next month, allowing the country in the middle of a resurgence of the coronavirus outbreak to begin inoculating people with the highest risks for infections.</p><p>The Chinese vaccine in three batches, with the first 200,000 doses arriving in February, 800,000 in March, and another 1 million in April, according to the Health Ministry. Thailand has also started local production of vaccines developed by AstraZeneca Plc under a technology transfer agreement, which is expected to be ready for distribution in May, the ministry said.</p><p>Authorities and health workers are racing to curb the spread of a new wave of local infections that started from seafood markets in Samut Sakhon, the province bordering the southwestern side of Bangkok. Prime Minister Prayut Chan-o-cha has imposed a new set of restrictions on businesses and gatherings in Bangkok and 27 of its worst-affected provinces from Monday to contain the outbreak.</p><p>Thailand has been relatively successful in containing the pathogen after becoming the first country outside China to report the deadly virus, but cases may spike to about 1,000 a day or more even with strict control measures, according to the Centre for Covid-19 Situation Administration. The country reported 745 new virus cases on Monday with 709 of them locally transmitted, taking the nation’s total to 8,439.</p><p>Gen Prayut’s government has set a target of inoculating 50% of its population, or about 33 million people, by the end of 2021 with vaccines from various sources, including the World Health Organization-backed Covax program. It’s also negotiating with other vaccine developers for additional supplies, according to the health ministry.</p></div>",
    newsReference:
      "https://www.bangkokpost.com/thailand/general/2045315/thailand-to-get-2-million-shots-of-chinas-sinovac"
  },
  {
    newsId: "news002",
    newsTitle: "One Covid death, 305 new cases",
    exampleContent:
      "The government on Thursday reported 305 new Covid-19 cases - 193 local infections, 109 from active testing and three arrivals - raising the total to 9,636, and one more death lifted the fatality toll to 67.",
    newsContent:
      "<div><p>The government on Thursday reported 305 new Covid-19 cases - 193 local infections, 109 from active testing and three arrivals - raising the total to 9,636, and one more death lifted the fatality toll to 67.</p><p>Taweesilp Visanuyothin, spokesman for the Centre for Covid-19 Situation Administration, said the latest death was a Thai man, aged 88, who also had cancer and was bed-ridden.</p><p>He caught Covid-19 from his son, who had been in an at-risk area in Rayong province. The son visited him at home on Dec 22, later tested positive for the disease and was admitted to a hospital in Rayong.</p><p>On Jan 2, the elderly man began coughing, with excessive phlegm, diarrhea and a mild fever. He tested positive the following day. His conditions deteriorated on Jan 4 and he died on Wednesday morning, the spokesman said.</p><p>New cases over the previous 24 hours included 46 in Bangkok, 37 in Samut Sakhon, 27 in Chon Buri, 25 in Samut Prakan, 23 in Rayong, 8 in Chanthaburi.</p><p>Active testing found 109 new cases in Samut Sakhon alone. Of them, 107 are migrants.</p><p>Three infected arrivals came from Russia, Turkey and Myanmar.</p><p>The case from Myanmar is a Thai woman, 27, who worked at an entertainment place in the neighbouring country and sneaked back to Mae Sot district of Tak on Jan 4. She was admitted to Maesot General Hospital.</p><p>New cases are still rising at a concerning pace, Dr Taweesilp said.</p><p>Of the total 9,636 cases, 4,521 (46.9%) had recovered, including 103 discharged over the previous 24 hours, and 5,048 were receiving treatment.</p><p>Dr Taweesilp said the government was trying to contain Covid-19 by causing  inconvenience for people who wanted to travel to and from five Covid-19-plagued provinces of Samut Sakhon, Chon Buri, Rayong, Trat and Chanthaburi and 23 adjacent provinces.</p><p>Officials were operating checkpoints on both main and minor roads linking the provinces. People who needed to travel between the provinces must show official documents to prove their travel was necessary. Their employers could issue such documents, he said.</p><p>At checkpoints, officials would check their temperature, travel papers and travel records, Dr Taweesilp said.</p><p>Meanwhile, global Covid-19 cases increased by 781,103 over 24 hours to 87.64 million. The worldwide death toll was up by 14,126 to 1.89 million.</p><p>The United States had the most cases at 21.86 million, up 260,973, and the most deaths at 369,990, up 4,100.</p></div>",
    newsReference:
      "https://www.bangkokpost.com/thailand/general/2047139/one-covid-death-305-new-cases"
  },
  {
    newsId: "news003",
    newsTitle: "19 Rohingya held in Bangkok for illegal entry",
    exampleContent:
      "Nineteen Rohingya migrants have been arrested in Bangkok for illegal entry to Thailand and a Thai woman accused of housing them has also been detained, police said on Saturday.",
    newsContent:
      "<div><p>Nineteen Rohingya migrants have been arrested in Bangkok for illegal entry to Thailand and a Thai woman accused of housing them has also been detained, police said on Saturday.</p><p>The arrests have raised concerns about trafficking routes for the Muslim minority fleeing Myanmar, at a time when illegal migrants from that country have been linked to a second wave of coronavirus infections accross Thailand.</p><p>Police said the trafficking operation was discovered on Jan 3 when the Rohingya were found in a house in Don Mueang district of Bangkok.</p><p>“Police also managed to arrest one Thai woman in Pathum Thani on the charge of providing shelter to the Rohingya,” Pol Col Kissana Phathanacharoen, the deputy police spokesman, told AFP.</p><p>The group was smuggled into Thailand overland from Rakhine state in Myanmar and was bound for Malaysia, said an immigration officer who declined to be named.</p><p>“They didn’t know what kind of work they would find in Malaysia, they just wanted to get out of Rakhine,” he said, adding that the Thai woman’s husband, who is still at large, had promised them jobs.</p><p>Out of the 19 Rohingya, seven tested positive for coronavirus and are being treated, said the officer, while the rest are being kept in quarantine as a precaution.</p><p>Thailand was thrust into the international spotlight in 2015 during the “boat crisis”, in which desperate Rohingya and Bangladeshi migrants were stranded at sea and abandoned by their traffickers.</p><p>Police officers, a high-ranking general and several local politicians were among scores convicted for their role in the trafficking network, which spilled into full view after officials found dozens of shallow graves in hidden camps near the Malaysian border.</p><p>Pol Col Kissana said the latest discovery of the 19 Rohingya — along with the threat of the coronavirus spreading — has authorities worried.</p><p>“The chief of Thai police has expressed his concern over the issue of police being potentially involved with the smuggling scandal, so he has ordered subordinates to strictly follow the law,” Pol Col Kissana told AFP.</p><p>Earlier this week nearly 100 Rohingya bound for Malaysia were arrested in a raid in Yangon. Authorities are still investigating whether the smugglers are part of a wider network.</p><p>The embattled Rohingya Muslims have long faced persecution in Myanmar, where they are denied freedom of movement and citizenship, and lack access to work, healthcare and schools.</p><p>A 2017 military crackdown in western Rakhine state sent almost 750,000 fleeing across the border to Bangladesh, while many choose to embark on treacherous journeys with human smugglers to reach Malaysia and Indonesia, sometimes going through Thailand.</p></div>",
    newsReference:
      "https://www.bangkokpost.com/thailand/general/2048215/19-rohingya-held-in-bangkok-for-illegal-entry "
  },
  {
    newsId: "news004",
    newsTitle:
      "Medical examiner reviewing doctor's death 2 weeks after getting COVID vaccine",
    exampleContent:
      "ORLANDO, Fla. — The medical examiner’s office in Miami is looking into the death of a doctor who died about two weeks after getting Pfizer’s COVID-19 vaccine, officials said Friday.",
    newsContent:
      "<div><p>ORLANDO, Fla. — The medical examiner’s office in Miami is looking into the death of a doctor who died about two weeks after getting Pfizer’s COVID-19 vaccine, officials said Friday.</p><p>In a statement, Pfizer said it was aware of the death, but that it didn’t think there was any direct connection to the vaccine.</p><p>The death of Dr. Gregory Michael is being investigated along with the Florida Department of Health and the federal Centers for Disease Control and Prevention. Samples from an autopsy conducted Wednesday have been sent to the CDC, said Darren Caprara, director of operations for the Miami-Dade County Medical Examiner Department.</p><p>“The cause of death is pending the completion of studies” by the medical examiner and the CDC, Caprara said in an email Friday.</p><p>Pfizer said the doctor died 16 days after receiving a vaccine shot. The company said it was a “highly unusual” and severe case of a condition that can prevent blood from clotting and cause internal bleeding.</p><p>“To date, millions of people have been vaccinated and we are closely monitoring all adverse events in individuals receiving our vaccine,” the statement said.</p><p>Michael, 56, died Sunday. He was an obstetrician with a private practice at Mount Sinai Medical Center in Miami Beach. His wife didn’t respond to a request for an interview on Friday.</p></div>",
    newsReference:
      "https://www.washingtontimes.com/news/2021/jan/8/dr-gregory-michael-dies-2-weeks-after-getting-covi/ "
  }
];
