module.exports = [
  {
    newsId: "news001",
    newsTitle: "Thailand to get 2 million shots of China’s Sinovac",
    exampleContent:
      "Thailand will get its first lot of Covid-19 vaccines from China’s Sinovac Biotech Ltd next month",
    newsContent:
      "<div><p>Thailand will get its first lot of Covid-19 vaccines from China’s Sinovac Biotech Ltd next month, allowing the country in the middle of a resurgence of the coronavirus outbreak to begin inoculating people with the highest risks for infections.</p><p>The Chinese vaccine in three batches, with the first 200,000 doses arriving in February, 800,000 in March, and another 1 million in April, according to the Health Ministry. Thailand has also started local production of vaccines developed by AstraZeneca Plc under a technology transfer agreement, which is expected to be ready for distribution in May, the ministry said.</p><p>Authorities and health workers are racing to curb the spread of a new wave of local infections that started from seafood markets in Samut Sakhon, the province bordering the southwestern side of Bangkok. Prime Minister Prayut Chan-o-cha has imposed a new set of restrictions on businesses and gatherings in Bangkok and 27 of its worst-affected provinces from Monday to contain the outbreak.</p><p>Thailand has been relatively successful in containing the pathogen after becoming the first country outside China to report the deadly virus, but cases may spike to about 1,000 a day or more even with strict control measures, according to the Centre for Covid-19 Situation Administration. The country reported 745 new virus cases on Monday with 709 of them locally transmitted, taking the nation’s total to 8,439.</p><p>Gen Prayut’s government has set a target of inoculating 50% of its population, or about 33 million people, by the end of 2021 with vaccines from various sources, including the World Health Organization-backed Covax program. It’s also negotiating with other vaccine developers for additional supplies, according to the health ministry.</p></div>",
    newsReference:
      "https://www.bangkokpost.com/thailand/general/2045315/thailand-to-get-2-million-shots-of-chinas-sinovac"
  },
  {
    newsId: "news002",
    newsTitle: "Thailand to get 2 million shots of China’s Sinovac",
    exampleContent:
      "Thailand will get its first lot of Covid-19 vaccines from China’s Sinovac Biotech Ltd next month",
    newsContent:
      "<div><p>Thailand will get its first lot of Covid-19 vaccines from China’s Sinovac Biotech Ltd next month, allowing the country in the middle of a resurgence of the coronavirus outbreak to begin inoculating people with the highest risks for infections.</p><p>The Chinese vaccine in three batches, with the first 200,000 doses arriving in February, 800,000 in March, and another 1 million in April, according to the Health Ministry. Thailand has also started local production of vaccines developed by AstraZeneca Plc under a technology transfer agreement, which is expected to be ready for distribution in May, the ministry said.</p><p>Authorities and health workers are racing to curb the spread of a new wave of local infections that started from seafood markets in Samut Sakhon, the province bordering the southwestern side of Bangkok. Prime Minister Prayut Chan-o-cha has imposed a new set of restrictions on businesses and gatherings in Bangkok and 27 of its worst-affected provinces from Monday to contain the outbreak.</p><p>Thailand has been relatively successful in containing the pathogen after becoming the first country outside China to report the deadly virus, but cases may spike to about 1,000 a day or more even with strict control measures, according to the Centre for Covid-19 Situation Administration. The country reported 745 new virus cases on Monday with 709 of them locally transmitted, taking the nation’s total to 8,439.</p><p>Gen Prayut’s government has set a target of inoculating 50% of its population, or about 33 million people, by the end of 2021 with vaccines from various sources, including the World Health Organization-backed Covax program. It’s also negotiating with other vaccine developers for additional supplies, according to the health ministry.</p></div>",
    newsReference:
      "https://www.bangkokpost.com/thailand/general/2045315/thailand-to-get-2-million-shots-of-chinas-sinovac"
  },
  {
    newsId: "news003",
    newsTitle: "Thailand to get 2 million shots of China’s Sinovac",
    exampleContent:
      "Thailand will get its first lot of Covid-19 vaccines from China’s Sinovac Biotech Ltd next month",
    newsContent:
      "<div><p>Thailand will get its first lot of Covid-19 vaccines from China’s Sinovac Biotech Ltd next month, allowing the country in the middle of a resurgence of the coronavirus outbreak to begin inoculating people with the highest risks for infections.</p><p>The Chinese vaccine in three batches, with the first 200,000 doses arriving in February, 800,000 in March, and another 1 million in April, according to the Health Ministry. Thailand has also started local production of vaccines developed by AstraZeneca Plc under a technology transfer agreement, which is expected to be ready for distribution in May, the ministry said.</p><p>Authorities and health workers are racing to curb the spread of a new wave of local infections that started from seafood markets in Samut Sakhon, the province bordering the southwestern side of Bangkok. Prime Minister Prayut Chan-o-cha has imposed a new set of restrictions on businesses and gatherings in Bangkok and 27 of its worst-affected provinces from Monday to contain the outbreak.</p><p>Thailand has been relatively successful in containing the pathogen after becoming the first country outside China to report the deadly virus, but cases may spike to about 1,000 a day or more even with strict control measures, according to the Centre for Covid-19 Situation Administration. The country reported 745 new virus cases on Monday with 709 of them locally transmitted, taking the nation’s total to 8,439.</p><p>Gen Prayut’s government has set a target of inoculating 50% of its population, or about 33 million people, by the end of 2021 with vaccines from various sources, including the World Health Organization-backed Covax program. It’s also negotiating with other vaccine developers for additional supplies, according to the health ministry.</p></div>",
    newsReference:
      "https://www.bangkokpost.com/thailand/general/2045315/thailand-to-get-2-million-shots-of-chinas-sinovac"
  },
  {
    newsId: "news004",
    newsTitle: "Thailand to get 2 million shots of China’s Sinovac",
    exampleContent:
      "Thailand will get its first lot of Covid-19 vaccines from China’s Sinovac Biotech Ltd next month",
    newsContent:
      "<div><p>Thailand will get its first lot of Covid-19 vaccines from China’s Sinovac Biotech Ltd next month, allowing the country in the middle of a resurgence of the coronavirus outbreak to begin inoculating people with the highest risks for infections.</p><p>The Chinese vaccine in three batches, with the first 200,000 doses arriving in February, 800,000 in March, and another 1 million in April, according to the Health Ministry. Thailand has also started local production of vaccines developed by AstraZeneca Plc under a technology transfer agreement, which is expected to be ready for distribution in May, the ministry said.</p><p>Authorities and health workers are racing to curb the spread of a new wave of local infections that started from seafood markets in Samut Sakhon, the province bordering the southwestern side of Bangkok. Prime Minister Prayut Chan-o-cha has imposed a new set of restrictions on businesses and gatherings in Bangkok and 27 of its worst-affected provinces from Monday to contain the outbreak.</p><p>Thailand has been relatively successful in containing the pathogen after becoming the first country outside China to report the deadly virus, but cases may spike to about 1,000 a day or more even with strict control measures, according to the Centre for Covid-19 Situation Administration. The country reported 745 new virus cases on Monday with 709 of them locally transmitted, taking the nation’s total to 8,439.</p><p>Gen Prayut’s government has set a target of inoculating 50% of its population, or about 33 million people, by the end of 2021 with vaccines from various sources, including the World Health Organization-backed Covax program. It’s also negotiating with other vaccine developers for additional supplies, according to the health ministry.</p></div>",
    newsReference:
      "https://www.bangkokpost.com/thailand/general/2045315/thailand-to-get-2-million-shots-of-chinas-sinovac"
  },
  {
    newsId: "news005",
    newsTitle: "Thailand to get 2 million shots of China’s Sinovac",
    exampleContent:
      "Thailand will get its first lot of Covid-19 vaccines from China’s Sinovac Biotech Ltd next month",
    newsContent:
      "<div><p>Thailand will get its first lot of Covid-19 vaccines from China’s Sinovac Biotech Ltd next month, allowing the country in the middle of a resurgence of the coronavirus outbreak to begin inoculating people with the highest risks for infections.</p><p>The Chinese vaccine in three batches, with the first 200,000 doses arriving in February, 800,000 in March, and another 1 million in April, according to the Health Ministry. Thailand has also started local production of vaccines developed by AstraZeneca Plc under a technology transfer agreement, which is expected to be ready for distribution in May, the ministry said.</p><p>Authorities and health workers are racing to curb the spread of a new wave of local infections that started from seafood markets in Samut Sakhon, the province bordering the southwestern side of Bangkok. Prime Minister Prayut Chan-o-cha has imposed a new set of restrictions on businesses and gatherings in Bangkok and 27 of its worst-affected provinces from Monday to contain the outbreak.</p><p>Thailand has been relatively successful in containing the pathogen after becoming the first country outside China to report the deadly virus, but cases may spike to about 1,000 a day or more even with strict control measures, according to the Centre for Covid-19 Situation Administration. The country reported 745 new virus cases on Monday with 709 of them locally transmitted, taking the nation’s total to 8,439.</p><p>Gen Prayut’s government has set a target of inoculating 50% of its population, or about 33 million people, by the end of 2021 with vaccines from various sources, including the World Health Organization-backed Covax program. It’s also negotiating with other vaccine developers for additional supplies, according to the health ministry.</p></div>",
    newsReference:
      "https://www.bangkokpost.com/thailand/general/2045315/thailand-to-get-2-million-shots-of-chinas-sinovac"
  }
];
